config/routes.rb
Rails.application.routes.draw do

	get '/login', to: 'users#login'
	post '/login', to: 'users#check_credentials'
	delete '/logout', to: 'users#logout'

  resources :accounts do
		resources :transactions
	end

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	validates_uniqueness_of :number
	
  belongs_to :user
	has_many :transactions, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :account_transactions]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.where(user_id: session[:current_user_id])
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
		@transactions = @account.transactions
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def account_transactions
		@transactions = @account.transactions
	end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:number, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= form.hidden_field :user_id, :value => session[:current_user_id] %>
	</div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :account_number %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/account_transactions.html.erb
<table>
	<h1>
		<%= @account.user.name %>
	</h1>
<h3>Current Balance: <%= number_to_currency(Transaction.balance(@transactions)) %></h3>
  <thead>

    <tr>
			<th>Description</th>
      <th>Credit</th>
      <th>Debit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.description %></td>
        <td><%= number_to_currency(transaction.credit) %></td>
        <td><%= number_to_currency(transaction.debit) %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
	</tbody>
</table>
<br>



<%= link_to 'New Transaction', new_account_transaction_path %>|
<%= link_to 'Your accounts', accounts_path %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Account Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.number %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Account Number:</strong>
  <%= @account.number %>
</h2>

<h3>
	<strong>Current Balance:</strong>
	<%= number_to_currency(@transactions.balance) %>
</h3>

<div class="transactions">
	<h1>Transactions</h1>
	<table>

  	<thead>

    	<tr>
				<th>Description</th>
      	<th>Credit</th>
      	<th>Debit</th>
      	<th colspan="3"></th>
    	</tr>
  	</thead>

  	<tbody>
    	<% @transactions.each do |transaction| %>
      	<tr>
        	<td><%= transaction.description %></td>
        	<td><%= number_to_currency(transaction.credit) %></td>
        	<td><%= number_to_currency(transaction.debit) %></td>
					<td><%= link_to 'Show', account_transaction_path(@account, transaction)%></td>
	        <td><%= link_to 'Edit', edit_account_transaction_path(@account, transaction) %></td>
	        <td><%= link_to 'Destroy', account_transaction_path(@account, transaction), method: :delete, data: { confirm: 'Are you sure?' } %></td>


      	</tr>
    	<% end %>
		</tbody>
	</table>

<%= render 'transactions/form', transaction: Transaction.new %>

	<br>
	<%= link_to 'New Transaction', new_account_transaction_path(account_id: params[:id]) %>
</div>
<br>

<%= link_to 'Accounts', accounts_path %>